name: todoa
description: A new Flutter application.


publish_to:


version: 1.0.0+1

environment:
  sdk: "2.12.2"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.0
  provider: ^5.0.0





  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true


